### ISSUE TITLE
Full API key requirement - why?

### ISSUE THREAD

**Issue by sn0opy** [sixones/vitality#46]
While adding a new character, the link in that window points to a full API key, why? It's an app to manage skill plan. There's no need for anything else chan characterSheet and the two skill API calls.

Beside that, it's even checking the api key for specific permissions like contracts or market orders. Why?

**Comment by Bleyddyn** [comment]
Recent versions of Vitality let you see Contracts, Market Orders and EVE Mail. And as a long range plan I hope to add support for all of the EVE API's, possibly even including CREST.

I could try to change the way it checks key's so that it only checks when you try to access a feature, but that would cause problems as well.

Since Vitality never shares your keys or any of the data it accesses, in any way, I've never seen it as an issue.
