### ISSUE TITLE
Building / updating database

### ISSUE THREAD

**Issue by archonsme** [sixones/vitality#51]
After following the instructions for build_dbexport.sh I created an Aegis-1.1 database.sqlite and moved it to ~/Library/Application\ Support/Vitality/ but on opening Vitality although Preferences >> Database correctly displays Aegis 1,1 and the characters and skill planner entries are present there are no skills displayed as shown in attached image.
<img width="1170" alt="screen shot 2015-07-26 at 11 00 57" src="https://cloud.githubusercontent.com/assets/2751022/8893374/a9d69374-3385-11e5-848a-c6bc5aff7054.png">

NOTE: Did this because DB was stuck at Proteus and even using Dropbox links in Preference >> Database did not work.

**Comment by archonsme** [comment]
Perhaps the database dump has changed format as there are several .yaml files but only certificates.yaml is imported by dumprows.sh.

blueprints.yaml    
graphicIDs.yaml    
skinLicenses.yaml  
typeIDs.yaml
categoryIDs.yaml   
groupIDs.yaml      
skinMaterials.yaml
certificates.yaml  
iconIDs.yaml       
skins.yaml

**Comment by Bleyddyn** [comment]
The latest version of the database is Aegis. It's at:

https://sixones.github.io/vitality/database.sql.bz2
https://sixones.github.io/vitality/database.xml

Once you update to that version I think you'll still have to restart Vitality. If you still see the nulls after that, can you send me any Vitality related message you see in the Console? The Console app is in /Applications/Utilities. If you click on the "All Messages" item in the log list on the left then type Vitality in the search field at the top right you should be able to copy/paste those messages here. 

As for the .yaml files. Yes we should switch to using them, or at least the typeIDs. For now, though, the sql part of the SDE still has everything we need except for certificates, which is why those are being read from the yaml file.

**Comment by Bleyddyn** [comment]
I just remembered, there is actually an issue with the Aegis SDE. The invGroups table did not have the "published" column set properly. All rows were set to zero and the Vitality DB scripts are supposed to filter out anything that hasn't been published. I had to modify a few things to get it to work and even so there are still a couple of problems.

**Comment by archonsme** [comment]
Vitality database updated correctly to Aegis 1.1.1 using the above URLs - I cannot be certain but I suspect these differ from the defaults when I installed Vitality 0.3.2b. Thanks!
