### ISSUE TITLE
Crashes on startup (SOLVED) but needs source update.

### ISSUE THREAD

**Issue by TheRealKANi** [sixones/vitality#57]
'NSInvalidArgumentException', reason: 'NSConcreteAttributedString initWithString:: nil value'
One of the new Clones TypeID 166 apprenty causes this with 'Unknown EVE Notification'

2017-05-17 10:12:34.341 Vitality[49103:486670] Unknown EVE Notification typeID: 166
2017-05-17 10:12:34.341 Vitality[49103:486670] *** Assertion failure in -[NSTextFieldCell _objectValue:forString:errorDescription:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504.82.104/AppKit.subproj/NSCell.m:1674
Illegal instruction: 4

If I access the 'database.sqlite' in '/Users/<USER>/Library/Application Support/Vitality/<SOMEID>/database.sqlite' and changes the typeID (166) of the 'notifications' table
to some other id ie. (165) The program works perfectly again..

Looks like the notificationID in question here 166 just don't exists..

/K

**Comment by TheRealKANi** [comment]
BTW..
![skaermbillede 2017-05-17 kl 10 18 22 1](https://cloud.githubusercontent.com/assets/1286819/26144727/3ced3894-3aea-11e7-9450-eb4ec4f73497.png)

The id exists in the pulled eve db.

**Comment by Bleyddyn** [comment]
This was fixed in code quite a while ago, there just hadn't been a release. This should be fixed as of v0.3.9b.

By the way, the "Notification typeID" mentioned in the first error message is not an actual invTypes.typeID. It's actually a notification specific ID, which is stored in a separate file in Vitality: NotificationTypeIDs.plist. Because documentation on notifications is limited and there's no way to systematically test it, there are many missing notification IDs. When that's the case there will now be a warning message in the notification UI instead of a crash.

As it is, I have no way of knowing what notification ID 166 is supposed to be, or what details it might contain.
